//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act60AdiministrativeStructure.
        /// </summary>
        internal static string Act60AdiministrativeStructure {
            get {
                return ResourceManager.GetString("Act60AdiministrativeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaMunicipalAdministration.
        /// </summary>
        internal static string AreaMunicipalAdministration {
            get {
                return ResourceManager.GetString("AreaMunicipalAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Council.
        /// </summary>
        internal static string Council {
            get {
                return ResourceManager.GetString("Council", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouncilOfMinistersAdministration.
        /// </summary>
        internal static string CouncilOfMinistersAdministration {
            get {
                return ResourceManager.GetString("CouncilOfMinistersAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutiveAgency.
        /// </summary>
        internal static string ExecutiveAgency {
            get {
                return ResourceManager.GetString("ExecutiveAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutivePowerAdministrativeStructure.
        /// </summary>
        internal static string ExecutivePowerAdministrativeStructure {
            get {
                return ResourceManager.GetString("ExecutivePowerAdministrativeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        internal static string Ministry {
            get {
                return ResourceManager.GetString("Ministry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MunicipalAdministration.
        /// </summary>
        internal static string MunicipalAdministration {
            get {
                return ResourceManager.GetString("MunicipalAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionalAdminisration.
        /// </summary>
        internal static string RegionalAdminisration {
            get {
                return ResourceManager.GetString("RegionalAdminisration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecializedLocalAdministration.
        /// </summary>
        internal static string SpecializedLocalAdministration {
            get {
                return ResourceManager.GetString("SpecializedLocalAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateAgency.
        /// </summary>
        internal static string StateAgency {
            get {
                return ResourceManager.GetString("StateAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateCommisionAdministrion.
        /// </summary>
        internal static string StateCommisionAdministrion {
            get {
                return ResourceManager.GetString("StateCommisionAdministrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatePublicConsultativeCommission.
        /// </summary>
        internal static string StatePublicConsultativeCommission {
            get {
                return ResourceManager.GetString("StatePublicConsultativeCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
