//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRegistry.CommonWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartRegistry.CommonWeb.Properties.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string area_createdby {
            get {
                return ResourceManager.GetString("area_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string area_date {
            get {
                return ResourceManager.GetString("area_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string area_description {
            get {
                return ResourceManager.GetString("area_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string area_name {
            get {
                return ResourceManager.GetString("area_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Areas.
        /// </summary>
        internal static string area_subarea {
            get {
                return ResourceManager.GetString("area_subarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string areagroup_hint_edit {
            get {
                return ResourceManager.GetString("areagroup_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminsitrative Body.
        /// </summary>
        internal static string base_administrative_body {
            get {
                return ResourceManager.GetString("base_administrative_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string base_attribute {
            get {
                return ResourceManager.GetString("base_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string base_attributes {
            get {
                return ResourceManager.GetString("base_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string base_condition {
            get {
                return ResourceManager.GetString("base_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string base_createdby {
            get {
                return ResourceManager.GetString("base_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string base_date {
            get {
                return ResourceManager.GetString("base_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string base_options {
            get {
                return ResourceManager.GetString("base_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string base_status_name {
            get {
                return ResourceManager.GetString("base_status_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        internal static string base_status_option_0 {
            get {
                return ResourceManager.GetString("base_status_option_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string base_status_option_1 {
            get {
                return ResourceManager.GetString("base_status_option_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unactive.
        /// </summary>
        internal static string base_status_option_2 {
            get {
                return ResourceManager.GetString("base_status_option_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string base_type {
            get {
                return ResourceManager.GetString("base_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        internal static string base_usergroup {
            get {
                return ResourceManager.GetString("base_usergroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Unit.
        /// </summary>
        internal static string filter_adminbody {
            get {
                return ResourceManager.GetString("filter_adminbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string filter_registerarea {
            get {
                return ResourceManager.GetString("filter_registerarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string filter_uri {
            get {
                return ResourceManager.GetString("filter_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Admin.
        /// </summary>
        internal static string globaladmin_role {
            get {
                return ResourceManager.GetString("globaladmin_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string import_file_name {
            get {
                return ResourceManager.GetString("import_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string import_hint_preview {
            get {
                return ResourceManager.GetString("import_hint_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Name.
        /// </summary>
        internal static string import_reg_name {
            get {
                return ResourceManager.GetString("import_reg_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccessed.
        /// </summary>
        internal static string import_status_proccessed {
            get {
                return ResourceManager.GetString("import_status_proccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadedFile.
        /// </summary>
        internal static string import_status_uploaded_file {
            get {
                return ResourceManager.GetString("import_status_uploaded_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated.
        /// </summary>
        internal static string import_status_validated {
            get {
                return ResourceManager.GetString("import_status_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string import_status_validation_error {
            get {
                return ResourceManager.GetString("import_status_validation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Admin.
        /// </summary>
        internal static string localadmin_role {
            get {
                return ResourceManager.GetString("localadmin_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative body module .
        /// </summary>
        internal static string permission_adminbody {
            get {
                return ResourceManager.GetString("permission_adminbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation of users.
        /// </summary>
        internal static string permission_deactivate {
            get {
                return ResourceManager.GetString("permission_deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data module.
        /// </summary>
        internal static string permission_importdata {
            get {
                return ResourceManager.GetString("permission_importdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified data objects module.
        /// </summary>
        internal static string permission_info_oboject {
            get {
                return ResourceManager.GetString("permission_info_oboject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal module.
        /// </summary>
        internal static string permission_journal {
            get {
                return ResourceManager.GetString("permission_journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation and managment of unified objects.
        /// </summary>
        internal static string permission_manage_info_object {
            get {
                return ResourceManager.GetString("permission_manage_info_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation and managment of users and usergroups.
        /// </summary>
        internal static string permission_manageuser {
            get {
                return ResourceManager.GetString("permission_manageuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string records_hint_edit {
            get {
                return ResourceManager.GetString("records_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string records_public_hint_edit {
            get {
                return ResourceManager.GetString("records_public_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Unit.
        /// </summary>
        internal static string register_admin_body {
            get {
                return ResourceManager.GetString("register_admin_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string register_hint_edit {
            get {
                return ResourceManager.GetString("register_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string register_hint_records {
            get {
                return ResourceManager.GetString("register_hint_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        internal static string register_hint_rights {
            get {
                return ResourceManager.GetString("register_hint_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal basis for the register.
        /// </summary>
        internal static string register_legalbasis {
            get {
                return ResourceManager.GetString("register_legalbasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Name.
        /// </summary>
        internal static string register_name {
            get {
                return ResourceManager.GetString("register_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string register_order {
            get {
                return ResourceManager.GetString("register_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description for public part.
        /// </summary>
        internal static string register_public_description {
            get {
                return ResourceManager.GetString("register_public_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Name.
        /// </summary>
        internal static string register_technicalname {
            get {
                return ResourceManager.GetString("register_technicalname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string register_theme {
            get {
                return ResourceManager.GetString("register_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string register_uri {
            get {
                return ResourceManager.GetString("register_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string register_url {
            get {
                return ResourceManager.GetString("register_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Rights.
        /// </summary>
        internal static string rights_name {
            get {
                return ResourceManager.GetString("rights_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        internal static string rights_usergroup {
            get {
                return ResourceManager.GetString("rights_usergroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string state_createdby {
            get {
                return ResourceManager.GetString("state_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string state_fillter_name {
            get {
                return ResourceManager.GetString("state_fillter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Point.
        /// </summary>
        internal static string state_initial {
            get {
                return ResourceManager.GetString("state_initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string state_insdatetime {
            get {
                return ResourceManager.GetString("state_insdatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string state_name {
            get {
                return ResourceManager.GetString("state_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string states_hint_edit {
            get {
                return ResourceManager.GetString("states_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Name.
        /// </summary>
        internal static string structure_apiname {
            get {
                return ResourceManager.GetString("structure_apiname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Attributes.
        /// </summary>
        internal static string structure_attributes {
            get {
                return ResourceManager.GetString("structure_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt values (Up to 80 characters!).
        /// </summary>
        internal static string structure_checkbox_encrypted {
            get {
                return ResourceManager.GetString("structure_checkbox_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can filter by this attribute.
        /// </summary>
        internal static string structure_checkbox_filter {
            get {
                return ResourceManager.GetString("structure_checkbox_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export values to OpenData.
        /// </summary>
        internal static string structure_checkbox_opendata {
            get {
                return ResourceManager.GetString("structure_checkbox_opendata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public access to this attribute.
        /// </summary>
        internal static string structure_checkbox_public {
            get {
                return ResourceManager.GetString("structure_checkbox_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values accessable through webservices or regix.
        /// </summary>
        internal static string structure_checkbox_webservice {
            get {
                return ResourceManager.GetString("structure_checkbox_webservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string structure_hint_edit {
            get {
                return ResourceManager.GetString("structure_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Services.
        /// </summary>
        internal static string structure_hint_services {
            get {
                return ResourceManager.GetString("structure_hint_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register States.
        /// </summary>
        internal static string structure_hint_states {
            get {
                return ResourceManager.GetString("structure_hint_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Transitions.
        /// </summary>
        internal static string structure_hint_transitions {
            get {
                return ResourceManager.GetString("structure_hint_transitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Object.
        /// </summary>
        internal static string structure_infoobject {
            get {
                return ResourceManager.GetString("structure_infoobject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string structure_name {
            get {
                return ResourceManager.GetString("structure_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string systemlog_data {
            get {
                return ResourceManager.GetString("systemlog_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string systemlog_filter_name {
            get {
                return ResourceManager.GetString("systemlog_filter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string systemlog_info {
            get {
                return ResourceManager.GetString("systemlog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string systemlog_user {
            get {
                return ResourceManager.GetString("systemlog_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End State.
        /// </summary>
        internal static string transition_end {
            get {
                return ResourceManager.GetString("transition_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string transition_hint_edit {
            get {
                return ResourceManager.GetString("transition_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        internal static string transition_rights {
            get {
                return ResourceManager.GetString("transition_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start State.
        /// </summary>
        internal static string transition_start {
            get {
                return ResourceManager.GetString("transition_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string unified_description {
            get {
                return ResourceManager.GetString("unified_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of object.
        /// </summary>
        internal static string unified_filter_name {
            get {
                return ResourceManager.GetString("unified_filter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string unified_hint_edit {
            get {
                return ResourceManager.GetString("unified_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Object.
        /// </summary>
        internal static string unified_info_object {
            get {
                return ResourceManager.GetString("unified_info_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Object.
        /// </summary>
        internal static string unified_information_object {
            get {
                return ResourceManager.GetString("unified_information_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses multiple values.
        /// </summary>
        internal static string unified_multiple_values {
            get {
                return ResourceManager.GetString("unified_multiple_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string unified_name {
            get {
                return ResourceManager.GetString("unified_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Name.
        /// </summary>
        internal static string unified_namespaceapi {
            get {
                return ResourceManager.GetString("unified_namespaceapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referential Attribute.
        /// </summary>
        internal static string unified_referential_attribute {
            get {
                return ResourceManager.GetString("unified_referential_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referential Register.
        /// </summary>
        internal static string unified_referential_register {
            get {
                return ResourceManager.GetString("unified_referential_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string unified_type {
            get {
                return ResourceManager.GetString("unified_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string unified_uri {
            get {
                return ResourceManager.GetString("unified_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *generated automatically*.
        /// </summary>
        internal static string uri_auto_generated {
            get {
                return ResourceManager.GetString("uri_auto_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string user_hint_edit {
            get {
                return ResourceManager.GetString("user_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Authentication.
        /// </summary>
        internal static string user_hint_resetauth {
            get {
                return ResourceManager.GetString("user_hint_resetauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user_role {
            get {
                return ResourceManager.GetString("user_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string usergroup_filter_name {
            get {
                return ResourceManager.GetString("usergroup_filter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string usergroup_hint_edit {
            get {
                return ResourceManager.GetString("usergroup_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string usergroup_name {
            get {
                return ResourceManager.GetString("usergroup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of user group.
        /// </summary>
        internal static string usergroup_type {
            get {
                return ResourceManager.GetString("usergroup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string users_email {
            get {
                return ResourceManager.GetString("users_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string users_name {
            get {
                return ResourceManager.GetString("users_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string users_phone {
            get {
                return ResourceManager.GetString("users_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical name of the service.
        /// </summary>
        internal static string webservice_apiname {
            get {
                return ResourceManager.GetString("webservice_apiname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes in the result.
        /// </summary>
        internal static string webservice_attribute_result {
            get {
                return ResourceManager.GetString("webservice_attribute_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string webservice_description {
            get {
                return ResourceManager.GetString("webservice_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string webservice_filter_name {
            get {
                return ResourceManager.GetString("webservice_filter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download XSD.
        /// </summary>
        internal static string webservice_hint_downloadXSD {
            get {
                return ResourceManager.GetString("webservice_hint_downloadXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string webservice_hint_edit {
            get {
                return ResourceManager.GetString("webservice_hint_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string webservice_name {
            get {
                return ResourceManager.GetString("webservice_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory in the request.
        /// </summary>
        internal static string webservice_required_in_report {
            get {
                return ResourceManager.GetString("webservice_required_in_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings of the request.
        /// </summary>
        internal static string webservice_settings {
            get {
                return ResourceManager.GetString("webservice_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of service.
        /// </summary>
        internal static string webservice_type {
            get {
                return ResourceManager.GetString("webservice_type", resourceCulture);
            }
        }
    }
}
