//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string base_start {
            get {
                return ResourceManager.GetString("base_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string footer_access {
            get {
                return ResourceManager.GetString("footer_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string footer_contact {
            get {
                return ResourceManager.GetString("footer_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string footer_stats {
            get {
                return ResourceManager.GetString("footer_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string footer_terms {
            get {
                return ResourceManager.GetString("footer_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINISTRY OF E-GOVERNANCE.
        /// </summary>
        internal static string head_meu {
            get {
                return ResourceManager.GetString("head_meu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION SYSTEM FOR CENTRALIZED.
        /// </summary>
        internal static string head_system_1 {
            get {
                return ResourceManager.GetString("head_system_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTABLISHMENT AND MAINTENANCE OF REGISTERS.
        /// </summary>
        internal static string head_system_2 {
            get {
                return ResourceManager.GetString("head_system_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data available.
        /// </summary>
        internal static string home_index_access {
            get {
                return ResourceManager.GetString("home_index_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic services and information for citizens and businesses.
        /// </summary>
        internal static string home_index_list_header {
            get {
                return ResourceManager.GetString("home_index_list_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        internal static string home_index_organization {
            get {
                return ResourceManager.GetString("home_index_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of registers.
        /// </summary>
        internal static string home_index_registers {
            get {
                return ResourceManager.GetString("home_index_registers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Data.
        /// </summary>
        internal static string menu_agency {
            get {
                return ResourceManager.GetString("menu_agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string menu_contact {
            get {
                return ResourceManager.GetString("menu_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registers.
        /// </summary>
        internal static string menu_registers {
            get {
                return ResourceManager.GetString("menu_registers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string site_menu {
            get {
                return ResourceManager.GetString("site_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright and related rights.
        /// </summary>
        internal static string Авторско_право_и_сродните_му_права {
            get {
                return ResourceManager.GetString("Авторско право и сродните му права", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative energy sources.
        /// </summary>
        internal static string Алтернативни_енергийни_източници {
            get {
                return ResourceManager.GetString("Алтернативни енергийни източници", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archival documents.
        /// </summary>
        internal static string Архивни_документи {
            get {
                return ResourceManager.GetString("Архивни документи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted production.
        /// </summary>
        internal static string Асистирана_репродукция {
            get {
                return ResourceManager.GetString("Асистирана репродукция", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployment, employment, insurance, social benefits.
        /// </summary>
        internal static string Безработица__заетост__осигуряване__социални_помощи {
            get {
                return ResourceManager.GetString("Безработица, заетост, осигуряване, социални помощи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployment and employment promotion.
        /// </summary>
        internal static string Безработица_и_насърчаване_на_заетостта {
            get {
                return ResourceManager.GetString("Безработица и насърчаване на заетостта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business and entrepreneurs.
        /// </summary>
        internal static string Бизнес_и_предприемачи {
            get {
                return ResourceManager.GetString("Бизнес и предприемачи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbs and medicinal plants.
        /// </summary>
        internal static string Билки_и_лечебни_растения {
            get {
                return ResourceManager.GetString("Билки и лечебни растения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian citizens abroad.
        /// </summary>
        internal static string Български_граждани_в_чужбина {
            get {
                return ResourceManager.GetString("Български граждани в чужбина", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian citizenship.
        /// </summary>
        internal static string Българско_гражданство {
            get {
                return ResourceManager.GetString("Българско гражданство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinary Medicine.
        /// </summary>
        internal static string Ветеринарна_медицина {
            get {
                return ResourceManager.GetString("Ветеринарна медицина", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinary medicine and control.
        /// </summary>
        internal static string Ветеринарна_медицина_и_контрол {
            get {
                return ResourceManager.GetString("Ветеринарна медицина и контрол", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property rights. Alienation, compensation.
        /// </summary>
        internal static string Вещни_права__Отчуждаване__обезщетяване {
            get {
                return ResourceManager.GetString("Вещни права. Отчуждаване, обезщетяване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Води {
            get {
                return ResourceManager.GetString("Води", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water supply and sewerage services.
        /// </summary>
        internal static string Водоснабдяване_и_канализационни_услуги {
            get {
                return ResourceManager.GetString("Водоснабдяване и канализационни услуги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed receivables in case of bankruptcy of the employer.
        /// </summary>
        internal static string Гарантирани_вземания_при_несъстоятелност_на_работодателя {
            get {
                return ResourceManager.GetString("Гарантирани вземания при несъстоятелност на работодателя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic and cartographic fund - maps, plans and coordinates.
        /// </summary>
        internal static string Геодезически_и_картографски_фонд___карти__планове_и_координати {
            get {
                return ResourceManager.GetString("Геодезически и картографски фонд - карти, планове и координати", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting, notarial activity, legal proceedings, deprivation of rights.
        /// </summary>
        internal static string Гласуване__нотариална_дейност__съдебни_производства__лишаване_от_права {
            get {
                return ResourceManager.GetString("Гласуване, нотариална дейност, съдебни производства, лишаване от права", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FISH fine, criminal decrees.
        /// </summary>
        internal static string Глоба_по_ФИШ__наказателни_постановления {
            get {
                return ResourceManager.GetString("Глоба по ФИШ, наказателни постановления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest fund and hunting farm.
        /// </summary>
        internal static string Горски_фонд_и_ловно_стопанство {
            get {
                return ResourceManager.GetString("Горски фонд и ловно стопанство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizens of other countries residing in Bulgaria.
        /// </summary>
        internal static string Граждани_на_други_държави_пребиваващи_в_България {
            get {
                return ResourceManager.GetString("Граждани на други държави пребиваващи в България", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil rights and legal order.
        /// </summary>
        internal static string Граждански_права_и_правен_ред {
            get {
                return ResourceManager.GetString("Граждански права и правен ред", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status, identity, family.
        /// </summary>
        internal static string Гражданско_състояние__самоличност__семейство {
            get {
                return ResourceManager.GetString("Гражданско състояние, самоличност, семейство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes, social and health insurance.
        /// </summary>
        internal static string Данъци__социално_и_здравно_осигуряване {
            get {
                return ResourceManager.GetString("Данъци, социално и здравно осигуряване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes and social security payments.
        /// </summary>
        internal static string Данъци_и_осигурителни_плащания {
            get {
                return ResourceManager.GetString("Данъци и осигурителни плащания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes and fees for citizens.
        /// </summary>
        internal static string Данъци_и_такси_за_граждани {
            get {
                return ResourceManager.GetString("Данъци и такси за граждани", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities in the field of culture, cultural values ​​and cultural heritage.
        /// </summary>
        internal static string Дейности_в_областта_на_културата__културни_ценности_и_културно_наследство {
            get {
                return ResourceManager.GetString("Дейности в областта на културата, културни ценности и културно наследство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities related to cultural values.
        /// </summary>
        internal static string Дейности_свързани_с_културни_ценности {
            get {
                return ResourceManager.GetString("Дейности свързани с културни ценности", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities related to sports facilities.
        /// </summary>
        internal static string Дейности_свързани_със_спортни_обекти {
            get {
                return ResourceManager.GetString("Дейности свързани със спортни обекти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergartens, schools, universities, professional qualifications.
        /// </summary>
        internal static string Детски_градини__училище__университети__професионална_квалификация {
            get {
                return ResourceManager.GetString("Детски градини, училище, университети, професионална квалификация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergartens, nurseries and pre-school training.
        /// </summary>
        internal static string Детски_градини__ясли_и_предучилищна_подготoвка {
            get {
                return ResourceManager.GetString("Детски градини, ясли и предучилищна подготoвка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children in risk.
        /// </summary>
        internal static string Деца_в_риск {
            get {
                return ResourceManager.GetString("Деца в риск", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild animals, plants and protected species.
        /// </summary>
        internal static string Диви_животни__растителни_и_защитени_видове {
            get {
                return ResourceManager.GetString("Диви животни, растителни и защитени видове", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to data.
        /// </summary>
        internal static string Достъп_до_данни {
            get {
                return ResourceManager.GetString("Достъп до данни", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility, publicity and transparency.
        /// </summary>
        internal static string Достъпност__публичност_и_прозрачност {
            get {
                return ResourceManager.GetString("Достъпност, публичност и прозрачност", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Други {
            get {
                return ResourceManager.GetString("Други", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Reserve and Wartime Stocks.
        /// </summary>
        internal static string Държавен_резерв_и_военновременни_запаси {
            get {
                return ResourceManager.GetString("Държавен резерв и военновременни запаси", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State and municipal property.
        /// </summary>
        internal static string Държавна_и_общинска_собственост {
            get {
                return ResourceManager.GetString("Държавна и общинска собственост", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecology and environment.
        /// </summary>
        internal static string Екология_и_околна_среда {
            get {
                return ResourceManager.GetString("Екология и околна среда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic messages.
        /// </summary>
        internal static string Електронни_съобщения {
            get {
                return ResourceManager.GetString("Електронни съобщения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic authentication services.
        /// </summary>
        internal static string Електронни_удостоверителни_услуги {
            get {
                return ResourceManager.GetString("Електронни удостоверителни услуги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic communication networks.
        /// </summary>
        internal static string Електронно_съобщителни_мрежи {
            get {
                return ResourceManager.GetString("Електронно съобщителни мрежи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energetics.
        /// </summary>
        internal static string Енергетика {
            get {
                return ResourceManager.GetString("Енергетика", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condominium.
        /// </summary>
        internal static string Етажна_собственост {
            get {
                return ResourceManager.GetString("Етажна собственост", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal husbandry.
        /// </summary>
        internal static string Животновъдство {
            get {
                return ResourceManager.GetString("Животновъдство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting, carrying out and ending business activity.
        /// </summary>
        internal static string Започване__извършване_и_приключване_на_стопанска_дейност {
            get {
                return ResourceManager.GetString("Започване, извършване и приключване на стопанска дейност", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected areas and species, pollution control.
        /// </summary>
        internal static string Защитени_територии_и_видове__контрол_на_замърсяването {
            get {
                return ResourceManager.GetString("Защитени територии и видове, контрол на замърсяването", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health control.
        /// </summary>
        internal static string Здравен_контрол {
            get {
                return ResourceManager.GetString("Здравен контрол", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare, health insurance, healthy and safe working conditions.
        /// </summary>
        internal static string Здравеопазване__здравно_осигуряване__здравословни_и_безопасни_условия_на_труд {
            get {
                return ResourceManager.GetString("Здравеопазване, здравно осигуряване, здравословни и безопасни условия на труд", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare and health insurance.
        /// </summary>
        internal static string Здравеопазване_и_здравно_осигуряване {
            get {
                return ResourceManager.GetString("Здравеопазване и здравно осигуряване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green system - vegetation and landscaping.
        /// </summary>
        internal static string Зелена_система___растителност_и_озеленяване {
            get {
                return ResourceManager.GetString("Зелена система - растителност и озеленяване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        internal static string Земеделие {
            get {
                return ResourceManager.GetString("Земеделие", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural activities, food, state sanitary control.
        /// </summary>
        internal static string Земеделски_дейности__храни__държавен_санитарен_контрол {
            get {
                return ResourceManager.GetString("Земеделски дейности, храни, държавен санитарен контрол", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance of documents to foreign citizens residing in Bulgaria.
        /// </summary>
        internal static string Издаване_на_документи_на_чуждестранни_граждани__пребиваващи_в_България {
            get {
                return ResourceManager.GetString("Издаване на документи на чуждестранни граждани, пребиваващи в България", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance of Personal Identification Code (PIC) and Insurer Identification Code (ICO).
        /// </summary>
        internal static string Издаване_на_Персонален_идентификационен_код__ПИК__и_Идентификационен_код_на_осигурителя__ИКО_ {
            get {
                return ResourceManager.GetString("Издаване на Персонален идентификационен код (ПИК) и Идентификационен код на осигу" +
                        "рителя (ИКО)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements and assessments of environmental impacts.
        /// </summary>
        internal static string Измервания_и_оценки_на_въздействия_върху_околната_среда {
            get {
                return ResourceManager.GetString("Измервания и оценки на въздействия върху околната среда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, address registration, identity documents.
        /// </summary>
        internal static string Име__адресна_регистрация__документи_за_самоличност {
            get {
                return ResourceManager.GetString("Име, адресна регистрация, документи за самоличност", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties, housing and utilities.
        /// </summary>
        internal static string Имоти__жилища_и_комунални_услуги {
            get {
                return ResourceManager.GetString("Имоти, жилища и комунални услуги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment projects and concessions.
        /// </summary>
        internal static string Инвестиционни_проекти_и_концесии {
            get {
                return ResourceManager.GetString("Инвестиционни проекти и концесии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment design, construction, geodesy.
        /// </summary>
        internal static string Инвестиционно_проектиране__строителство__геодезия {
            get {
                return ResourceManager.GetString("Инвестиционно проектиране, строителство, геодезия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment design and construction.
        /// </summary>
        internal static string Инвестиционно_проектиране_и_строителство {
            get {
                return ResourceManager.GetString("Инвестиционно проектиране и строителство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology and Communications.
        /// </summary>
        internal static string Информационни_технологии_и_съобщения {
            get {
                return ResourceManager.GetString("Информационни технологии и съобщения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastral activities.
        /// </summary>
        internal static string Кадастрални_дейности {
            get {
                return ResourceManager.GetString("Кадастрални дейности", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges and Universities.
        /// </summary>
        internal static string Колежи_и_университети {
            get {
                return ResourceManager.GetString("Колежи и университети", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution control.
        /// </summary>
        internal static string Контрол_на_замърсяването {
            get {
                return ResourceManager.GetString("Контрол на замърсяването", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrections, certifications, certificates and references concerning acts of civil status.
        /// </summary>
        internal static string Корекции__заверки__удостоверения_и_справки__касаещи_актове_по_гражданско_състояние {
            get {
                return ResourceManager.GetString("Корекции, заверки, удостоверения и справки, касаещи актове по гражданско състояни" +
                        "е", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture and cultural heritage.
        /// </summary>
        internal static string Култура_и_културно_наследство {
            get {
                return ResourceManager.GetString("Култура и културно наследство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinal products and medical devices.
        /// </summary>
        internal static string Лекарствени_продукти_и_медицински_изделия {
            get {
                return ResourceManager.GetString("Лекарствени продукти и медицински изделия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical institutions.
        /// </summary>
        internal static string Лечебни_заведения {
            get {
                return ResourceManager.GetString("Лечебни заведения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical facilities, medicines, doctors, insurance rights.
        /// </summary>
        internal static string Лечебни_заведения__лекарства__медици__осигурителни_права {
            get {
                return ResourceManager.GetString("Лечебни заведения, лекарства, медици, осигурителни права", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons and organizations in the field of culture.
        /// </summary>
        internal static string Лица_и_организации_в_областта_на_културата {
            get {
                return ResourceManager.GetString("Лица и организации в областта на културата", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        internal static string Лицензиране {
            get {
                return ResourceManager.GetString("Лицензиране", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viticulture and wine production.
        /// </summary>
        internal static string Лозарство_и_производство_на_вино {
            get {
                return ResourceManager.GetString("Лозарство и производство на вино", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local taxes and fees.
        /// </summary>
        internal static string Местни_данъци_и_такси {
            get {
                return ResourceManager.GetString("Местни данъци и такси", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs regimes and permits. Import, export, forwarding.
        /// </summary>
        internal static string Митнически_режими_и_разрешителни__Внос__износ__спедиция {
            get {
                return ResourceManager.GetString("Митнически режими и разрешителни. Внос, износ, спедиция", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATO certifications, state reserve and wartime stocks.
        /// </summary>
        internal static string НАТО_сертификации__държавен_резерв_и_военновременни_запаси {
            get {
                return ResourceManager.GetString("НАТО сертификации, държавен резерв и военновременни запаси", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconventional methods to promote health.
        /// </summary>
        internal static string Неконвенционални_методи_за_благоприятстване_на_здравето {
            get {
                return ResourceManager.GetString("Неконвенционални методи за благоприятстване на здравето", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary documents for travel, residence.
        /// </summary>
        internal static string Необходими_документи_при_пътуване__пребиваване {
            get {
                return ResourceManager.GetString("Необходими документи при пътуване, пребиваване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankruptcy and liquidation.
        /// </summary>
        internal static string Несъстоятелност_и_ликвидация {
            get {
                return ResourceManager.GetString("Несъстоятелност и ликвидация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education and qualification.
        /// </summary>
        internal static string Образование_и_квалификация {
            get {
                return ResourceManager.GetString("Образование и квалификация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education or internship in another European Union country.
        /// </summary>
        internal static string Образование_или_стаж_в_друга_държава_от_Европейския_съюз {
            get {
                return ResourceManager.GetString("Образование или стаж в друга държава от Европейския съюз", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        internal static string Обществени_поръчки {
            get {
                return ResourceManager.GetString("Обществени поръчки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous weather phenomena.
        /// </summary>
        internal static string Опасни_метеорологични_явления {
            get {
                return ResourceManager.GetString("Опасни метеорологични явления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance archive - documents of terminated insurers without legal successor.
        /// </summary>
        internal static string Осигурителен_архив___документи_на_прекратени_осигурители_без_правоприемник {
            get {
                return ResourceManager.GetString("Осигурителен архив - документи на прекратени осигурители без правоприемник", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance for LLC funds.
        /// </summary>
        internal static string Осигуряване_за_фондовете_на_ДОО {
            get {
                return ResourceManager.GetString("Осигуряване за фондовете на ДОО", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense and security.
        /// </summary>
        internal static string Отбрана_и_сигурност {
            get {
                return ResourceManager.GetString("Отбрана и сигурност", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste and hazardous substances.
        /// </summary>
        internal static string Отпадъци_и_опасни_вещества {
            get {
                return ResourceManager.GetString("Отпадъци и опасни вещества", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor protection.
        /// </summary>
        internal static string Охрана_на_труда {
            get {
                return ResourceManager.GetString("Охрана на труда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monetary benefits, benefits and pensions according to European regulations and international agreements.
        /// </summary>
        internal static string Парични_обезщетения__помощи_и_пенсии_по_европейски_регламенти_и_международни_договори {
            get {
                return ResourceManager.GetString("Парични обезщетения, помощи и пенсии по европейски регламенти и международни дого" +
                        "вори", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash benefits in case of sickness, maternity and unemployment and benefits from DOO.
        /// </summary>
        internal static string Парични_обезщетения_при_болест__майчинство_и_безработица_и_помощи_от_ДОО {
            get {
                return ResourceManager.GetString("Парични обезщетения при болест, майчинство и безработица и помощи от ДОО", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patents and copyrights.
        /// </summary>
        internal static string Патенти_и_авторски_права {
            get {
                return ResourceManager.GetString("Патенти и авторски права", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pensions under Bulgarian legislation.
        /// </summary>
        internal static string Пенсии_по_българското_законодателство {
            get {
                return ResourceManager.GetString("Пенсии по българското законодателство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Персонал {
            get {
                return ResourceManager.GetString("Персонал", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal capacity, transport, road taxes, road infrastructure.
        /// </summary>
        internal static string Правоспособност__превоз__пътни_данъци__пътна_инфраструктура {
            get {
                return ResourceManager.GetString("Правоспособност, превоз, пътни данъци, пътна инфраструктура", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal capacity and professional qualification in the field of transport.
        /// </summary>
        internal static string Правоспособност_и_професионална_квалификация_в_областта_на_транспорта {
            get {
                return ResourceManager.GetString("Правоспособност и професионална квалификация в областта на транспорта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence in another member state of the European Union.
        /// </summary>
        internal static string Пребиваване_в_друга_държава_членка_на_Европейския_съюз {
            get {
                return ResourceManager.GetString("Пребиваване в друга държава членка на Европейския съюз", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation of passengers.
        /// </summary>
        internal static string Превоз_на_пътници {
            get {
                return ResourceManager.GetString("Превоз на пътници", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo transportation.
        /// </summary>
        internal static string Превоз_на_товари {
            get {
                return ResourceManager.GetString("Превоз на товари", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of the territories, development, reconstruction.
        /// </summary>
        internal static string Предназначение_на_териториите__застрояване__преустройство {
            get {
                return ResourceManager.GetString("Предназначение на териториите, застрояване, преустройство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision of data by GEOCARTFOND.
        /// </summary>
        internal static string Предоставяне_на_данни_от_ГЕОКАРТФОНД {
            get {
                return ResourceManager.GetString("Предоставяне на данни от ГЕОКАРТФОНД", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards of athletes and coaches.
        /// </summary>
        internal static string Премии_на_спортисти_и_треньори {
            get {
                return ResourceManager.GetString("Премии на спортисти и треньори", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition, sale and mortgage of real estate.
        /// </summary>
        internal static string Придобиване__продажба_и_ипотека_на_недвижим_имот {
            get {
                return ResourceManager.GetString("Придобиване, продажба и ипотека на недвижим имот", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition, registration and tax of vehicles.
        /// </summary>
        internal static string Придобиване__регистрация_и_данък_на_превозни_средства {
            get {
                return ResourceManager.GetString("Придобиване, регистрация и данък на превозни средства", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant protection products.
        /// </summary>
        internal static string Продукти_за_растителна_защита {
            get {
                return ResourceManager.GetString("Продукти за растителна защита", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative projects or funded by the national budget, banking, financial and investment services, business financing.
        /// </summary>
        internal static string Проекти_иновационни_или_финансирани_от_националния_бюджет__банкови__финансови_и_инвестиционни_услуги__финансиране_на_стопанска_дейност {
            get {
                return ResourceManager.GetString("Проекти иновационни или финансирани от националния бюджет, банкови, финансови и и" +
                        "нвестиционни услуги, финансиране на стопанска дейност", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production and trade, goods and services.
        /// </summary>
        internal static string Производство_и_търговия__стоки_и_услуги {
            get {
                return ResourceManager.GetString("Производство и търговия, стоки и услуги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production and trade of health products.
        /// </summary>
        internal static string Производство_и_търговия_на_продукти_със_значение_за_здравето {
            get {
                return ResourceManager.GetString("Производство и търговия на продукти със значение за здравето", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production and trade of food and agricultural products.
        /// </summary>
        internal static string Производство_и_търговия_с_храни_и_земеделски_продукти {
            get {
                return ResourceManager.GetString("Производство и търговия с храни и земеделски продукти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionals - geodesy, cartography and cadastre.
        /// </summary>
        internal static string Професионалисти___геодезия__картография_и_кадастър {
            get {
                return ResourceManager.GetString("Професионалисти - геодезия, картография и кадастър", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional orientation and qualification, training of adults.
        /// </summary>
        internal static string Професионално_ориентиране_и_квалификация__обучение_на_възрастни {
            get {
                return ResourceManager.GetString("Професионално ориентиране и квалификация, обучение на възрастни", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevention, rehabilitation and occupational accident.
        /// </summary>
        internal static string Профилактика__рехабилитация_и_трудова_злополука {
            get {
                return ResourceManager.GetString("Профилактика, рехабилитация и трудова злополука", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel within the European Union.
        /// </summary>
        internal static string Пътуване_в_рамките_на_Европейския_съюз {
            get {
                return ResourceManager.GetString("Пътуване в рамките на Европейския съюз", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel and residence abroad.
        /// </summary>
        internal static string Пътуване_и_пребиваване_в_чужбина {
            get {
                return ResourceManager.GetString("Пътуване и пребиваване в чужбина", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work, pension, social assistance.
        /// </summary>
        internal static string Работа__пенсия__социално_подпомагане {
            get {
                return ResourceManager.GetString("Работа, пенсия, социално подпомагане", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work and qualifications for foreign nationals.
        /// </summary>
        internal static string Работа_и_квалификация_за_чуждестранни_граждани {
            get {
                return ResourceManager.GetString("Работа и квалификация за чуждестранни граждани", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio, TV and other electronic media.
        /// </summary>
        internal static string Радио__телевизия_и_други_електронни_медии {
            get {
                return ResourceManager.GetString("Радио, телевизия и други електронни медии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth, adoption, foster families, guardianship and guardianship.
        /// </summary>
        internal static string Раждане__осиновяване__приемни_семейства__настойничество_и_попечителство {
            get {
                return ResourceManager.GetString("Раждане, осиновяване, приемни семейства, настойничество и попечителство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission modes.
        /// </summary>
        internal static string Разрешителни_режими {
            get {
                return ResourceManager.GetString("Разрешителни режими", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant breeding.
        /// </summary>
        internal static string Растениевъдство {
            get {
                return ResourceManager.GetString("Растениевъдство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations, permits, procedures.
        /// </summary>
        internal static string Регистрации__разрешителни__процедури {
            get {
                return ResourceManager.GetString("Регистрации, разрешителни, процедури", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisheries and aquaculture.
        /// </summary>
        internal static string Рибарство_и_аквакултури {
            get {
                return ResourceManager.GetString("Рибарство и аквакултури", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberal professions and trades. Self-insured.
        /// </summary>
        internal static string Свободни_професии_и_занаяти__Самоосигуряващи_се {
            get {
                return ResourceManager.GetString("Свободни професии и занаяти. Самоосигуряващи се", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture and forestry.
        /// </summary>
        internal static string Селско_стопанство_и_гори {
            get {
                return ResourceManager.GetString("Селско стопанство и гори", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural machinery and infrastructure.
        /// </summary>
        internal static string Селскостопанска_техника_и_инфраструктура {
            get {
                return ResourceManager.GetString("Селскостопанска техника и инфраструктура", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family - marriage, divorce.
        /// </summary>
        internal static string Семейство___брак__развод {
            get {
                return ResourceManager.GetString("Семейство - брак, развод", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications and activities related to NATO.
        /// </summary>
        internal static string Сертификации_и_дейности_свързани_с_НАТО {
            get {
                return ResourceManager.GetString("Сертификации и дейности свързани с НАТО", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death and Succession.
        /// </summary>
        internal static string Смърт_и_наследяване {
            get {
                return ResourceManager.GetString("Смърт и наследяване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security.
        /// </summary>
        internal static string Социално_осигуряване {
            get {
                return ResourceManager.GetString("Социално осигуряване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social security/Pensions, cash benefits and benefits from DOO, guaranteed receivables in case of employer&apos;s bankruptcy.
        /// </summary>
        internal static string Социално_осигуряване_Пенсии__парични_обезщетения_и_помощи_от_ДОО__гарантирани_вземания_при_несъстоятелност_на_работодателя {
            get {
                return ResourceManager.GetString("Социално осигуряване/Пенсии, парични обезщетения и помощи от ДОО, гарантирани взе" +
                        "мания при несъстоятелност на работодателя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social assistance.
        /// </summary>
        internal static string Социално_подпомагане {
            get {
                return ResourceManager.GetString("Социално подпомагане", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References and documents for health status, health insurance.
        /// </summary>
        internal static string Справки_и_документи_за_здравен_статус__здравни_осигуровки {
            get {
                return ResourceManager.GetString("Справки и документи за здравен статус, здравни осигуровки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction and remodeling.
        /// </summary>
        internal static string Строеж_и_преустройства {
            get {
                return ResourceManager.GetString("Строеж и преустройства", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction and remodeling, real estate transactions, taxes.
        /// </summary>
        internal static string Строежи_и_преустройства__сделки_с_недвижими_имоти__данъци {
            get {
                return ResourceManager.GetString("Строежи и преустройства, сделки с недвижими имоти, данъци", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction and commissioning of facilities.
        /// </summary>
        internal static string Строителство_и_въвеждане_на_обекти_в_експлоатация {
            get {
                return ResourceManager.GetString("Строителство и въвеждане на обекти в експлоатация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication networks, radio and television, electronic communications and IT activities.
        /// </summary>
        internal static string Съобщителни_мрежи__радио_и_телевизия__електронни_съобщения_и_дейности_в_областта_на_ИТ {
            get {
                return ResourceManager.GetString("Съобщителни мрежи, радио и телевизия, електронни съобщения и дейности в областта " +
                        "на ИТ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical infrastructure.
        /// </summary>
        internal static string Техническа_инфраструктура {
            get {
                return ResourceManager.GetString("Техническа инфраструктура", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transplants, tissue and cell donors.
        /// </summary>
        internal static string Трансплантации__донори_на_тъкани_и_клетки {
            get {
                return ResourceManager.GetString("Трансплантации, донори на тъкани и клетки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport and vehicles.
        /// </summary>
        internal static string Транспорт_и_превозни_средства {
            get {
                return ResourceManager.GetString("Транспорт и превозни средства", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport infrastructure.
        /// </summary>
        internal static string Транспортна_инфраструктура {
            get {
                return ResourceManager.GetString("Транспортна инфраструктура", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment and pension insurance.
        /// </summary>
        internal static string Трудово_и_пенсионно_осигуряване {
            get {
                return ResourceManager.GetString("Трудово и пенсионно осигуряване", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourism, hotel industry, restaurant industry.
        /// </summary>
        internal static string Туризъм__хотелиерство__ресторантьорство {
            get {
                return ResourceManager.GetString("Туризъм, хотелиерство, ресторантьорство", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade and transportation of weapons, ammunition and other explosive substances.
        /// </summary>
        internal static string Търговия_и_транспортиране_на_оръжия__боеприпаси_и_други_взривоопасни_вещества {
            get {
                return ResourceManager.GetString("Търговия и транспортиране на оръжия, боеприпаси и други взривоопасни вещества", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication and reference services for businesses.
        /// </summary>
        internal static string Удостоверителни_и_справочни_услуги_за_бизнеса {
            get {
                return ResourceManager.GetString("Удостоверителни и справочни услуги за бизнеса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential services related to education.
        /// </summary>
        internal static string Удостоверителни_услуги__свързани_с_образованието {
            get {
                return ResourceManager.GetString("Удостоверителни услуги, свързани с образованието", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication and exercise of civil rights.
        /// </summary>
        internal static string Удостоверяване_и_упражняване_на_граждански_права {
            get {
                return ResourceManager.GetString("Удостоверяване и упражняване на граждански права", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification of rights to property and things.
        /// </summary>
        internal static string Удостоверяване_на_права_върху_имущество_и_вещи {
            get {
                return ResourceManager.GetString("Удостоверяване на права върху имущество и вещи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services for foreign citizens.
        /// </summary>
        internal static string Услуги_за_чужди_граждани {
            get {
                return ResourceManager.GetString("Услуги за чужди граждани", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational plans - creation, amendments.
        /// </summary>
        internal static string Устройствени_планове___създаване__изменения {
            get {
                return ResourceManager.GetString("Устройствени планове - създаване, изменения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure of the territory, construction and cadastre.
        /// </summary>
        internal static string Устройство_на_територията__строителство_и_кадастър {
            get {
                return ResourceManager.GetString("Устройство на територията, строителство и кадастър", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        internal static string Училища {
            get {
                return ResourceManager.GetString("Училища", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film productions.
        /// </summary>
        internal static string Филмови_продукции {
            get {
                return ResourceManager.GetString("Филмови продукции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytosanitary, fodder food control, plant protection.
        /// </summary>
        internal static string Фитосанитарен__фуражен_контрол_на_храните__растителна_защита {
            get {
                return ResourceManager.GetString("Фитосанитарен, фуражен контрол на храните, растителна защита", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disadvantaged people.
        /// </summary>
        internal static string Хора_в_неравностойно_положение {
            get {
                return ResourceManager.GetString("Хора в неравностойно положение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private security activity.
        /// </summary>
        internal static string Частна_охранителна_дейност {
            get {
                return ResourceManager.GetString("Частна охранителна дейност", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign citizens residing in Bulgaria.
        /// </summary>
        internal static string Чуждестранни_граждани__пребиваващи_в_България {
            get {
                return ResourceManager.GetString("Чуждестранни граждани, пребиваващи в България", resourceCulture);
            }
        }
    }
}
