// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.100.0. www.xsd2code.com
//    {"TargetFramework":"Net47","NameSpace":"RegiX.MmsSportOrganizationsAdapter","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace RegiX.MmsSportOrganizationsAdapter
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MMS/SportOrganizationsReportRequest")]
    [XmlRootAttribute("SportOrganizationsRequest", Namespace = "http://egov.bg/RegiX/MMS/SportOrganizationsReportRequest", IsNullable = false)]
    public partial class SportOrganizationsRequestType
    {
        #region Private fields
        private System.DateTime _fromDate;
        #endregion

        [XmlElement(DataType = "date")]
        public System.DateTime FromDate
        {
            get
            {
                return _fromDate;
            }
            set
            {
                _fromDate = value;
            }
        }
    }
}
#pragma warning restore
