// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.100.0. www.xsd2code.com
//    {"TargetFramework":"Net47","NameSpace":"RegiX.MmsSportOrganizationsAdapter","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace RegiX.MmsSportOrganizationsAdapter
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://egov.bg/RegiX/MMS/SportOrganizationsReportResponse")]
    [XmlRootAttribute(Namespace = "http://egov.bg/RegiX/MMS/SportOrganizationsReportResponse", IsNullable = false)]
    public partial class SportOrganizationsReportResponse
    {
        #region Private fields
        private List<SportOrganizationData> _sportOrganizationData;
        #endregion

        public SportOrganizationsReportResponse()
        {
            _sportOrganizationData = new List<SportOrganizationData>();
        }

        [XmlElement("SportOrganizationData")]
        public List<SportOrganizationData> SportOrganizationData
        {
            get
            {
                return _sportOrganizationData;
            }
            set
            {
                _sportOrganizationData = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://egov.bg/RegiX/MMS/SportOrganizationsReportResponse")]
    public partial class SportOrganizationData
    {
        #region Private fields
        private string _sportUnionType;
        private string _sportUnionRegNumber;
        private string _licenseNumber;
        private string _regNumberEntryOrder;
        private System.DateTime _entryOrderDate;
        private string _unionName;
        private string _unionLocation;
        private string _unionAddress;
        private string _unionStatus;
        private System.DateTime _unionStatusDate;
        private string _presenter;
        private string _addressCorespondant;
        private string _telephone;
        private string _emails;
        private string _sport;
        private string _eIK;
        private string _webPage;
        private string _foreignData;
        private string _cancelationOrder;
        private System.DateTime _cancelDate;
        #endregion

        public string SportUnionType
        {
            get
            {
                return _sportUnionType;
            }
            set
            {
                _sportUnionType = value;
            }
        }

        public string SportUnionRegNumber
        {
            get
            {
                return _sportUnionRegNumber;
            }
            set
            {
                _sportUnionRegNumber = value;
            }
        }

        public string LicenseNumber
        {
            get
            {
                return _licenseNumber;
            }
            set
            {
                _licenseNumber = value;
            }
        }

        public string RegNumberEntryOrder
        {
            get
            {
                return _regNumberEntryOrder;
            }
            set
            {
                _regNumberEntryOrder = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime EntryOrderDate
        {
            get
            {
                return _entryOrderDate;
            }
            set
            {
                _entryOrderDate = value;
            }
        }

        public string UnionName
        {
            get
            {
                return _unionName;
            }
            set
            {
                _unionName = value;
            }
        }

        public string UnionLocation
        {
            get
            {
                return _unionLocation;
            }
            set
            {
                _unionLocation = value;
            }
        }

        public string UnionAddress
        {
            get
            {
                return _unionAddress;
            }
            set
            {
                _unionAddress = value;
            }
        }

        public string UnionStatus
        {
            get
            {
                return _unionStatus;
            }
            set
            {
                _unionStatus = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime UnionStatusDate
        {
            get
            {
                return _unionStatusDate;
            }
            set
            {
                _unionStatusDate = value;
            }
        }

        public string Presenter
        {
            get
            {
                return _presenter;
            }
            set
            {
                _presenter = value;
            }
        }

        public string AddressCorespondant
        {
            get
            {
                return _addressCorespondant;
            }
            set
            {
                _addressCorespondant = value;
            }
        }

        public string Telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                _telephone = value;
            }
        }

        public string Emails
        {
            get
            {
                return _emails;
            }
            set
            {
                _emails = value;
            }
        }

        public string Sport
        {
            get
            {
                return _sport;
            }
            set
            {
                _sport = value;
            }
        }

        public string EIK
        {
            get
            {
                return _eIK;
            }
            set
            {
                _eIK = value;
            }
        }

        public string WebPage
        {
            get
            {
                return _webPage;
            }
            set
            {
                _webPage = value;
            }
        }

        public string ForeignData
        {
            get
            {
                return _foreignData;
            }
            set
            {
                _foreignData = value;
            }
        }

        public string CancelationOrder
        {
            get
            {
                return _cancelationOrder;
            }
            set
            {
                _cancelationOrder = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime CancelDate
        {
            get
            {
                return _cancelDate;
            }
            set
            {
                _cancelDate = value;
            }
        }
    }
}
#pragma warning restore
